### ISSUE TITLE
selection list

### ISSUE THREAD

**Issue by vitobellini** [KoheiHayakawa/KHAForm#1]
Hi, you control is very helpful but is missing a thing.
A sort of picker or selection list for custom elements.
(i.e.: If I want to select a country from a very large list > 100 items, it would be helpful to use a new cell type, that prompt a new table from which the user selects an element)

what do you think about it?

**Comment by KoheiHayakawa** [comment]
Yes, definitely. 
Actually, that is my next task.
Thank you for your contribution!
