### ISSUE TITLE
Date Cell

### ISSUE THREAD

**Issue by vitobellini** [KoheiHayakawa/KHAForm#2]
Hello, I would to thank you of the selection cell type to have implemented.
I've something to point out about the date cell. The current type should be named "DateTime", and a new cell "Date" should be implemented. Suppose we have to make a birthday field in the form, the time is useless, just to make the user to select the date is the best practice. Do you agree?

**Comment by KoheiHayakawa** [comment]
Yes, I agree.
I implemented this and we can change date format by setting date formatter and date picker mode of date cell's property.
You can check this update at latest commit currently.
This update will be included in the next version.
Thank you.
