### ISSUE TITLE
KHASelectionFormViewController and cell's checkmark

### ISSUE THREAD

**Issue by vitobellini** [KoheiHayakawa/KHAForm#3]
at line 51 you have         if selectedIndex == indexPath.row {

it should be 

```
    if selectedIndex == indexPath.row {
        cell.accessoryType = .Checkmark
    } else {
        cell.accessoryType = .None
    }
```

because if you have a tableview with several cells, the checkmark will be showed "randomly" because of the reuse of cell.

Addition: if we have a selected index, moving the tableview for showing the selected row would be perfect! http://stackoverflow.com/questions/5856427/how-to-scroll-uitableview-to-specific-position

**Comment by KoheiHayakawa** [comment]
I'm not sure the meaning of "randomly" you're saying. 
It seems to be ok because default accessory type is None.
How does the reuse of cell make bad influence?

That's better UI. Thank you!
> Addition

**Comment by KoheiHayakawa** [comment]
Thanks!
Latest update includes these fixes.
