### ISSUE TITLE
Selection and NavBar

### ISSUE THREAD

**Issue by vitobellini** [KoheiHayakawa/KHAForm#5]
Hello,
I'm facing a scenario in which I don't have a navigation bar visible, but the Selection cell does.

In KHASelectionFormViewController.swift i made some changes:

```
    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(true)
        self.navigationController?.navigationBarHidden = true
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.navigationBarHidden = false
        tableView.registerClass(UITableViewCell.self, forCellReuseIdentifier: cellID)
        tableView.reloadData()
        dispatch_async(dispatch_get_main_queue(), { () -> Void in
            self.tableView.scrollToRowAtIndexPath(NSIndexPath(forRow: self.selectedIndex, inSection: 0), atScrollPosition: .Middle, animated: false)
        })
    }
```

in order to preserver the backbutton of Selection view controller and hide the nav bar when I'm back outside of the Selection.

Is it possible to implement such a mechanism using a flag on selection cell? May be something like:

```
cell.parentHasHiddenNavBar = true
```

in order to hide the parent nav bar only when the flag is true?

What do you think?

**Comment by KoheiHayakawa** [comment]
At the last update, implementation of selection form was changed.
Now, selection cell has a property of selectionFormViewController instead of selections and selectedIndex.
You can see the detail at this update. Please check it out.
I think it's more customisable.
Does this solution make sense for you?

**Comment by vitobellini** [comment]
nice implementation, it's very customizable.
good job!
